In [1]:
from IPython import get_ipython
get_ipython().run_line_magic("reset","-f")

from PyPackageJonas import *

graphics_path = "C:/Users/jonas/Git/Analysis-of-Production-flow-systems-with-focus-on-industry/Latex Thesis/figures/ND examples/MI calc"

In [2]:
G = np.array([[0,2],[2,0]])
np.linalg.eig(G)

EigResult(eigenvalues=array([ 2., -2.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))

In [3]:
G @ np.linalg.pinv(np.eye(2) + G)

array([[ 1.33333333, -0.66666667],
       [-0.66666667,  1.33333333]])

In [9]:
-0.5 * np.log(1 - 0.2**2)

0.020410997260127583

In [11]:
G_u = np.triu(G)
G_u @ np.linalg.pinv( np.eye(2) + G_u)

array([[0., 2.],
       [0., 0.]])

In [12]:
G_u @ G_u

array([[0, 0],
       [0, 0]])